from constants import *
import numpy as np

"""a simple library for spline interpolation through state space
used for interpolation of control points in MPC"""

def next_guide_point(guide_state):
    """a function to generate the next idealised state given a current state
    function takes the form x[k+1] = f(x[k])
    the trajectory states generated by this funciton are used as the basis for the optimisation
    in the MPC controller.

    Parameters:
    -----------
    guide_state (ndarray): the current state of the guide trajectory x[k]

    Returns:
    --------
    next_guide_state (ndarray): the next state of the guide trajectory x[k+1]
    """
    x, y, psi, v, delta = guide_state
    if x < XG - K:  # before turn
        next_state = [x + VG * DT,
                      Y0, 
                      0,
                      VG,
                      0,]
    elif x >= XG - K and y < Y0 + K:    # during turn
        #theta = np.atan((x + K - XG)/(y - Y0))
        theta = np.atan2(x + K - XG, K - (y + Y0))
        next_theta = theta + OMEGAG * DT

        next_state = [XG + K*(np.sin(next_theta) - 1),
                      Y0 + K*(1 - np.cos(next_theta)),
                      next_theta,
                      VG, 
                      np.asin(1 / K)]
    elif y >= Y0 + K:   # after turn
        next_state = [XG,
                      y + VG * DT,
                      np.pi / 2,
                      VG,
                      0]
    return np.array(next_state)

def generate_guide_trajectory(state):
    """a function to generate a guide trajectory for the mpc controller
    this function makes repeated calls to next_guide_point to construct a guide trajectory over
    the full solution horizon for the MPC to optimise to. 
    """
    trajectory = []
    for n in range(N):
        state = next_guide_point(state)
        trajectory.extend(state)
    return trajectory

if __name__ == "__main__":
    import matplotlib.pyplot as plt 

    state = [XG - (K + 1), 
             Y0, 
             0, 
             VG, 
             0]
    
    trajectory = np.array(generate_guide_trajectory(state))
    trajectory = trajectory.reshape((N, NX))
    fig, ax = plt.subplots()
    ax.scatter(trajectory[:, 0], trajectory[:, 1])
    ax.set(aspect="equal")